language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run test
  - npm run lint
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: my-theresa-fe
  skip_cleanup: true
  acl: public_read
  local_dir: dist
