language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run test
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
